// Add your dependencies here

dependencies {
    api('com.github.GTNewHorizons:Baubles-Expanded:2.2.21-GTNH:dev')
    api('thaumcraft:Thaumcraft:1.7.10-4.2.3.5:dev') {transitive=false}

    compileOnly('com.github.GTNewHorizons:ThaumicBoots:1.5.12:dev') {transitive=false}
    compileOnly('com.github.GTNewHorizons:GTNHLib:0.11.47:dev') { transitive = false }
    compileOnly('com.github.GTNewHorizons:ForbiddenMagic:0.9.17-GTNH:dev') { transitive = false }
    compileOnly('com.github.GTNewHorizons:Botania:1.13.25-GTNH:dev') {transitive=false}
    compileOnly('com.github.GTNewHorizons:EnderCore:0.5.14:dev') {transitive=false}
    compileOnly('com.github.GTNewHorizons:EnderIO:2.10.31:dev') {transitive=false}
    compileOnly('com.github.GTNewHorizons:EnderStorage:1.8.3:dev') {transitive=false}
    compileOnly('com.github.GTNewHorizons:waila:1.19.30:api') {transitive=false}
    compileOnly('com.github.GTNewHorizons:TinkersConstruct:1.14.93-GTNH:dev') {transitive=false}
    compileOnly('com.github.GTNewHorizons:ForgeMultipart:1.7.10:dev') {transitive=false}
    compileOnly('com.github.GTNewHorizons:CodeChickenCore:1.4.16:dev') {transitive=false}
    compileOnly('com.github.GTNewHorizons:OpenComputers:1.12.47-GTNH:api') {transitive=false}
    compileOnly('net.industrial-craft:industrialcraft-2:2.2.828-experimental:api') {transitive=false}
    compileOnly("com.github.GTNewHorizons:GT5-Unofficial:5.09.54.01:dev") {exclude group: 'com.github.GTNewHorizons', module: 'ThaumicTinkerer'}
    compileOnly('curse.maven:computercraft-67504:2269339')
    compileOnly('curse.maven:cofh-core-69162:2388751')

    // For testing purposes
    //runtimeOnlyNonPublishable("com.github.GTNewHorizons:Electro-Magic-Tools:1.7.24:dev")
    runtimeOnlyNonPublishable('com.github.GTNewHorizons:Galacticraft:3.4.33-GTNH:dev'){transitive=false}
    runtimeOnlyNonPublishable('com.github.GTNewHorizons:TinkersConstruct:1.14.97-GTNH:dev')
    runtimeOnlyNonPublishable('com.github.GTNewHorizons:Applied-Energistics-2-Unofficial:rv3-beta-1054-GTNH:dev') {transitive=false}

    devOnlyNonPublishable('com.github.GTNewHorizons:AspectRecipeIndex:1.1.3:dev')
}
